#!/bin/bash
cd `dirname "$0"`

export os_platform=`uname`

export cl_platform=""

if [ "$1" == "sbcl" ]; then
   cl_platform='SBCL'
fi


if [ "$os_platform" == "Linux" ]; then
  if [ "$cl_platform" == "" ]; then
    cl_platform='Allegro'
  fi
  emacs --no-splash --no-init-file -l devo.el
elif [ "$os_platform" == "Darwin" ]; then
  if [ "$cl_platform" == "" ]; then
    cl_platform='LispWorks'
  fi
  /Applications/Emacs.app/Contents/MacOS/Emacs --no-splash --no-init-file -l devo.el
fi




