#!/bin/bash
cd `dirname "$0"`

export os_platform=`uname`

export cl_platform=''

if [ "$os_platform" == "Linux" ]; then
  cl_platform='Allegro'
  emacs --no-splash --no-init-file -l devo.el $@
elif [ "$os_platform" == "Darwin" ]; then
    if [ "$1" == "sbcl" ]; then
       cl_platform='SBCL'
    else
       cl_platform='LispWorks'
     fi
  /Applications/Emacs.app/Contents/MacOS/Emacs --no-splash --no-init-file -l devo.el
fi


